valor = input("Digite alguma coisa: ")
print("O tipo primitivo é {}".format(type(valor)))
print("Só tem espaços? {}".format(valor.isspace()))
print("É um número? {}".format(valor.isnumeric()))
print("É alfabetico? {}".format(valor.isalpha()))
print("É alfanumerico? {}".format(valor.isalnum()))
print("Está em maiúsculas? {}".format(valor.isupper()))
print("Está em minúsculas? {}".format(valor.islower()))
print("Está capitalizada? {}".format(valor.istitle()))